/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formAksi;

import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksidatabase.Koneksi;

/**
 *
 * @author USER
 */
public class Laporan extends javax.swing.JFrame {

    /**
     * Creates new form Laporan
     */
    private static Connection con;

    public Laporan() {
        initComponents();
        con = Koneksi.createKoneksi();
        inisialisasiTeksField();
        inisialisasiJTabel();
    }

    private void inisialisasiTeksField() {
        try {
            String query = "SELECT COUNT(idPelanggan) AS jumPelanggan FROM pelanggan;";
            Statement statement = con.createStatement();
            ResultSet resultSet = statement.executeQuery(query);
            if (resultSet.next()) {
                out1.setText(Integer.toString(resultSet.getInt("jumPelanggan")));
            }

            String sql1 = "SELECT COUNT(*) AS jumPengguna FROM `pengguna`;";
            resultSet = statement.executeQuery(sql1);
            if (resultSet.next()) {
                out2.setText(Integer.toString(resultSet.getInt("jumPengguna")));
            }

            String sql2 = "SELECT COUNT(*) AS jumItem FROM `item`;";
            resultSet = statement.executeQuery(sql2);
            if (resultSet.next()) {
                out3.setText(Integer.toString(resultSet.getInt("jumItem")));
            }

            String sql3 = "SELECT SUM(stok) as jumStokBar FROM item;";
            resultSet = statement.executeQuery(sql3);
            if (resultSet.next()) {
                out4.setText(Integer.toString(resultSet.getInt("jumStokBar")));
            }

            String sql4 = "SELECT SUM(pp.harga) AS totalPendapatan\n"
                    + "FROM pesananpenjualan AS pp\n"
                    + "WHERE MONTH(pp.tanggalPesan) = MONTH(CURRENT_DATE()) AND YEAR(pp.tanggalPesan) = YEAR(CURRENT_DATE()) AND status_pesanan = 'Lunas';";
            resultSet = statement.executeQuery(sql4);
            if (resultSet.next()) {
                out5.setText(Double.toString(resultSet.getDouble("totalPendapatan")));
            }

            String sql5 = "SELECT SUM(pp.harga) AS totalPendapatan\n"
                    + "FROM pesananpembelian AS pp\n"
                    + "WHERE MONTH(pp.tanggalPesan) = MONTH(CURRENT_DATE()) AND YEAR(pp.tanggalPesan) = YEAR(CURRENT_DATE()) AND status_pemebelian = 'Lunas';";
            resultSet = statement.executeQuery(sql5);
            if (resultSet.next()) {
                out6.setText(Double.toString(resultSet.getDouble("totalPendapatan")));
            }
            statement.close();
            resultSet.close();
        } catch (SQLException e) {
            System.out.println("Gagal inisialisasi teksfield laporan");
        }
    }

    private void inisialisasiJTabel() {
        try {
            DefaultTableModel tmodel = (DefaultTableModel) laporanTransaksiPenjualan.getModel();
            laporanTransaksiPenjualan.setAutoCreateRowSorter(true);
            tmodel.setRowCount(0);
            String query = "SELECT tp.tanggalTransaksi AS tanggalT, pp.kodeItem as codItm, pp.jumlah as jmlh, tp.totalBayar as bayaran FROM \n"
                    + "transaksipenjualan AS tp INNER JOIN pesananpenjualan AS pp ON tp.idPesananPenjualan = pp.idPesananPenjualan \n"
                    + "WHERE pp.status_pesanan = 'Lunas';";
            Statement statement = con.createStatement();
            ResultSet resultSet = statement.executeQuery(query);
            while (resultSet.next()) {
                int kodeItem = resultSet.getInt("codItm");
                Date tanggalPesan = resultSet.getDate("tanggalT");
                int jumlah = resultSet.getInt("jmlh");
                double harga = resultSet.getDouble("bayaran");
                ArrayList myLaporan = new ArrayList();
                myLaporan.add(tanggalPesan);
                myLaporan.add(kodeItem);
                myLaporan.add(jumlah);
                myLaporan.add(harga);
                tmodel.addRow(myLaporan.toArray());
            }
            statement.close();
            resultSet.close();
        } catch (SQLException e) {
            System.out.println("Gagal inisialisasi jtabel laporan");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        out1 = new javax.swing.JTextField();
        out2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        out3 = new javax.swing.JTextField();
        out4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        out5 = new javax.swing.JTextField();
        out6 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        butPP = new button.MyButton();
        butPPembelian = new button.MyButton();
        inpDateJual1 = new com.toedter.calendar.JDateChooser();
        inpDateJual2 = new com.toedter.calendar.JDateChooser();
        inpDateBeli2 = new com.toedter.calendar.JDateChooser();
        inpDateBeli1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        laporanTransaksiPenjualan = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setText("Jumlah Pelanggan");

        jLabel8.setText("Jumlah USER");

        jLabel9.setText("Jumlah item");

        out1.setEditable(false);

        out2.setEditable(false);

        jLabel10.setText("Total Item");

        out3.setEditable(false);

        out4.setEditable(false);

        jLabel11.setText("Pendapatan Bulan Ini");

        jLabel12.setText("Pengeluaran Bulan Ini");

        out5.setEditable(false);

        out6.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(out2, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(out1))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(out3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(out4))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(out5, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(out6))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(out1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(out3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(out5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(out2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(out4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(out6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Pendapatan Penjualan");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, -1, -1));

        jLabel3.setText("Pengeluaran Pembelian");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 16, -1, -1));

        jLabel4.setText("Dari tanggal");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel5.setText("Dari tanggal");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 54, -1, -1));

        jLabel6.setText("Hingga");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, -1));

        jLabel7.setText("Hingga");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        butPP.setForeground(new java.awt.Color(255, 255, 255));
        butPP.setText("CEK");
        butPP.setBorderColor(new java.awt.Color(153, 255, 51));
        butPP.setColor(new java.awt.Color(0, 0, 0));
        butPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPPActionPerformed(evt);
            }
        });
        jPanel2.add(butPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        butPPembelian.setForeground(new java.awt.Color(255, 255, 255));
        butPPembelian.setText("CEK");
        butPPembelian.setColor(new java.awt.Color(0, 0, 0));
        butPPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPPembelianActionPerformed(evt);
            }
        });
        jPanel2.add(butPPembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        inpDateJual1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(inpDateJual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 45, -1, -1));

        inpDateJual2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(inpDateJual2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        inpDateBeli2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(inpDateBeli2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        inpDateBeli1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(inpDateBeli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        laporanTransaksiPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal", "Kode Item", "Jumlah", "Total Biaya"
            }
        ));
        jScrollPane1.setViewportView(laporanTransaksiPenjualan);

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel13.setText("X");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel14.setText("LAPORAN PENJUALAN HARIAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jLabel14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPPActionPerformed
        if (inpDateJual1.getDate() == null || inpDateJual2.getDate() == null) {

        } else {
            Date tanggalAwal = new Date(inpDateJual1.getDate().getTime());
            Date tanggalAkhir = new Date(inpDateJual2.getDate().getTime());
            String tglAwal = tanggalAwal.toString();
            String tglAkhir = tanggalAkhir.toString();
            Statement statement;
            try {
                String sql = "SELECT SUM(harga) AS totalPendapatan\n"
                        + "FROM pesananpenjualan\n"
                        + "WHERE tanggalPesan BETWEEN '" + tglAwal + "' AND '" + tglAkhir + "';";
                statement = con.createStatement();
                ResultSet result = statement.executeQuery(sql);
                if (result.next()) {
                    JOptionPane.showMessageDialog(null, "Total pendapatan dalam rentang waktu tersebut adalah Rp." + result.getDouble("totalPendapatan"));
                }
            } catch (SQLException ex) {
                System.out.println("gagal mendapatkan pendapatan dalm 2 rentang waktu");
            }

        }
    }//GEN-LAST:event_butPPActionPerformed

    private void butPPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPPembelianActionPerformed
        if (inpDateBeli1.getDate() == null || inpDateBeli2.getDate() == null) {

        } else {
            Date tanggalAwal = new Date(inpDateBeli1.getDate().getTime());
            Date tanggalAkhir = new Date(inpDateBeli2.getDate().getTime());
            String tglAwal = tanggalAwal.toString();
            String tglAkhir = tanggalAkhir.toString();
            Statement statement;
            try {
                String sql = "SELECT SUM(harga) AS totalPendapatan\n"
                        + "FROM pesananpembelian\n"
                        + "WHERE tanggalPesan BETWEEN '" + tglAwal + "' AND '" + tglAkhir + "';";
                statement = con.createStatement();
                ResultSet result = statement.executeQuery(sql);
                if (result.next()) {
                    JOptionPane.showMessageDialog(null, "Total pembelian dalam rentang waktu tersebut adalah Rp." + result.getDouble("totalPendapatan"));
                }
            } catch (SQLException ex) {
                System.out.println("gagal mendapatkan pengeluaran dalm 2 rentang waktu");
            }

        }
    }//GEN-LAST:event_butPPembelianActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.MyButton butPP;
    private button.MyButton butPPembelian;
    private com.toedter.calendar.JDateChooser inpDateBeli1;
    private com.toedter.calendar.JDateChooser inpDateBeli2;
    private com.toedter.calendar.JDateChooser inpDateJual1;
    private com.toedter.calendar.JDateChooser inpDateJual2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable laporanTransaksiPenjualan;
    private javax.swing.JTextField out1;
    private javax.swing.JTextField out2;
    private javax.swing.JTextField out3;
    private javax.swing.JTextField out4;
    private javax.swing.JTextField out5;
    private javax.swing.JTextField out6;
    // End of variables declaration//GEN-END:variables
}
