/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formAksi;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksidatabase.Koneksi;
import raven.table.TableGradientCell;

/**
 *
 * @author USER
 */
public class Supplier extends javax.swing.JFrame {

    /**
     * Creates new form DaftarItem
     */
    private static Connection con;
    
    public Supplier() {
        initComponents();
        tabelSuplier.setDefaultRenderer(Object.class, new TableGradientCell());
        jPanel1.putClientProperty(FlatClientProperties.STYLE, ""
                + "border:1,1,1,1,$TableHeader.bottomSeparatorColor,,10");
        tabelSuplier.getTableHeader().putClientProperty(FlatClientProperties.STYLE, ""
                + "hoverBackground:null;"
                + "pressedBackground:null;"
                + "separatorColor:$TableHeader.background");
        scroll.putClientProperty(FlatClientProperties.STYLE, ""
                + "border:3,0,3,0,$Table.background,10,10");
        scroll.getVerticalScrollBar().putClientProperty(FlatClientProperties.STYLE, ""
                + "hoverTrackColor:null");
        con = Koneksi.createKoneksi();
        inisialisasiTabel();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pencarianInputan = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        inp1 = new javax.swing.JTextField();
        inp2 = new javax.swing.JTextField();
        inp6 = new javax.swing.JTextField();
        inp3 = new javax.swing.JTextField();
        inp4 = new javax.swing.JTextField();
        inp5 = new javax.swing.JTextField();
        butTambah = new button.MyButton();
        butDel = new button.MyButton();
        jPanel1 = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        tabelSuplier = new javax.swing.JTable();
        myButton1 = new button.MyButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setText("---------------------DATA SUPLIER------------------");

        pencarianInputan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("masukan idSuplier :");
        pencarianInputan.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        jLabel4.setText("nama :");
        pencarianInputan.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel6.setText("alamat :");
        pencarianInputan.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel7.setText("kota :");
        pencarianInputan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        jLabel8.setText("provinsi :");
        pencarianInputan.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        jLabel9.setText("nomor telpon :");
        pencarianInputan.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        pencarianInputan.add(inp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 110, -1));
        pencarianInputan.add(inp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 200, -1));
        pencarianInputan.add(inp6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 200, -1));
        pencarianInputan.add(inp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 700, -1));
        pencarianInputan.add(inp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 170, -1));
        pencarianInputan.add(inp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 170, -1));

        butTambah.setBackground(new java.awt.Color(0, 0, 0));
        butTambah.setForeground(new java.awt.Color(255, 255, 255));
        butTambah.setText("Tambah");
        butTambah.setBorderColor(new java.awt.Color(255, 255, 255));
        butTambah.setColor(new java.awt.Color(0, 0, 0));
        butTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTambahActionPerformed(evt);
            }
        });

        butDel.setBackground(new java.awt.Color(0, 0, 0));
        butDel.setForeground(new java.awt.Color(255, 255, 255));
        butDel.setText("Delete");
        butDel.setBorderColor(new java.awt.Color(255, 255, 255));
        butDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDelActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        tabelSuplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idSuplier", "nama", "alamat", "kota", "provinsi", "nomortelpon"
            }
        ));
        scroll.setViewportView(tabelSuplier);

        jPanel1.add(scroll, java.awt.BorderLayout.CENTER);

        myButton1.setText("EXIT");
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("-----------------ISI DATA SUPLIER-----------------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(butTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pencarianInputan, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(238, 238, 238))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jLabel2)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pencarianInputan, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(butTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(butDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inisialisasiTabel() {
        DefaultTableModel tmodel = (DefaultTableModel) tabelSuplier.getModel();
        tabelSuplier.setAutoCreateRowSorter(true);
        try {
            String query = "SELECT * FROM suplier";
            PreparedStatement preparedStatement = con.prepareStatement(query);
            ResultSet resultSet = preparedStatement.executeQuery();
            while (resultSet.next()) {
                int idSupplier = resultSet.getInt("idSuplier");
                String namaSupplier = resultSet.getString("nama");
                String alamat = resultSet.getString("alamat");
                String kota = resultSet.getString("kota");
                String provinsi = resultSet.getString("provinsi");
                String nomorTelpon = resultSet.getString("nomortelpon");
                ArrayList mySuplier = new ArrayList();
                mySuplier.add(idSupplier);
                mySuplier.add(namaSupplier);
                mySuplier.add(alamat);
                mySuplier.add(kota);
                mySuplier.add(provinsi);
                mySuplier.add(nomorTelpon);
                tmodel.addRow(mySuplier.toArray());
            }
            preparedStatement.close();
            resultSet.close();
        } catch (SQLException ex) {
            System.out.println(ex + "gagal inisialisasi tabel suplier");
        }
    }

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_myButton1ActionPerformed

    private void butTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTambahActionPerformed
        if (inp1.getText().isEmpty() || inp3.getText().isEmpty() || inp4.getText().isEmpty() || inp5.getText().isEmpty()
                || inp6.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tidak dapat menambahkan, isi yang kosong", "Notif", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                int idSupplier = Integer.parseInt(inp1.getText());
                String namaSupplier = inp2.getText();
                String alamat = inp3.getText();
                String kota = inp4.getText();
                String provinsi = inp5.getText();
                String nomorTelpon = inp6.getText();

                if (cekIDSuplier(idSupplier)) {
                    JOptionPane.showMessageDialog(null, "ID Suplier sudah ada", "Notif", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    String query = "INSERT INTO suplier (idSuplier, nama, alamat, kota, provinsi, nomortelpon) VALUES (?, ?, ?, ?, ?, ?)";
                    PreparedStatement preparedStatement = con.prepareStatement(query);
                    preparedStatement.setInt(1, idSupplier);
                    preparedStatement.setString(2, namaSupplier);
                    preparedStatement.setString(3, alamat);
                    preparedStatement.setString(4, kota);
                    preparedStatement.setString(5, provinsi);
                    preparedStatement.setString(6, nomorTelpon);

                    int hasilEksekusi = preparedStatement.executeUpdate();
                    if (hasilEksekusi > 0) {
                        JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan ke dalam tabel supplier", "Notif", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "Gagal menambahkan data ke dalam tabel supplier", "Notif", JOptionPane.INFORMATION_MESSAGE);
                    }
                    preparedStatement.close();
                }
            } catch (Exception e) {
                System.out.println("gagal tambah item");
            }
            DefaultTableModel tmodel = (DefaultTableModel) tabelSuplier.getModel();
            tmodel.setRowCount(0);
            inisialisasiTabel();
        }
    }//GEN-LAST:event_butTambahActionPerformed

    private void butDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDelActionPerformed
        int row = tabelSuplier.getSelectedRow();
        int value = Integer.parseInt(tabelSuplier.getModel().getValueAt(row, 0).toString());
        try {
            String query = "DELETE FROM suplier WHERE idSuplier = ?";
            PreparedStatement preparedStatement = con.prepareStatement(query);
            preparedStatement.setInt(1, value);
            int rowDeleted = preparedStatement.executeUpdate();
            if (rowDeleted > 0) {
                System.out.println("Data berhasil dihapus dari tabel supplier");
            } else {
                System.out.println("Gagal menghapus data dari tabel supplier");
            }
            preparedStatement.close();
        } catch (SQLException ex) {
            System.out.println("Gagal delete baris yang dipilih pada tabel supplier");
        }
        DefaultTableModel tmodel = (DefaultTableModel) tabelSuplier.getModel();
        tmodel.setRowCount(0);
        inisialisasiTabel();
    }//GEN-LAST:event_butDelActionPerformed

    private boolean cekIDSuplier(int value) {
        try {
            String query = "SELECT COUNT(*) FROM suplier WHERE idSuplier = ?";
            PreparedStatement preparedStatement = con.prepareStatement(query);
            preparedStatement.setInt(1, value);
            ResultSet resultSet = preparedStatement.executeQuery();
            resultSet.next();
            int count = resultSet.getInt(1);
            resultSet.close();
            preparedStatement.close();
            return count > 0;
        } catch (SQLException ex) {
            Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        FlatLaf.registerCustomDefaultsSource("formAksi");
        FlatMacDarkLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.MyButton butDel;
    private button.MyButton butTambah;
    private javax.swing.JTextField inp1;
    private javax.swing.JTextField inp2;
    private javax.swing.JTextField inp3;
    private javax.swing.JTextField inp4;
    private javax.swing.JTextField inp5;
    private javax.swing.JTextField inp6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private button.MyButton myButton1;
    private javax.swing.JPanel pencarianInputan;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tabelSuplier;
    // End of variables declaration//GEN-END:variables
}
